version: 2
jobs:
  build:
    working_directory: ~/cypress-onboarding-demo
    parallelism: 3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache ## cache both yarn and Cypress!
      - persist_to_workspace:
          root: ~/
          paths:
            - cypress-onboarding-demo

  run_tests:
    working_directory: ~/cypress-onboarding-demo
    docker:
      - image: cypress/browsers:node14.15.0-chrome86-ff82
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn cypress run --record --parallel
