version: 2.1
jobs:
  build:
    working_directory: ~/cypress-onboarding-demo
    docker:
      - image: cypress/base:14
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache ## cache both yarn and Cypress!
      # - persist_to_workspace:
      #     root: ~/
      #     paths:
      #       - ~/.cache
      #       - cypress-onboarding-demo

  run_tests:
    working_directory: ~/cypress-onboarding-demo
    docker:
      - image: cypress/browsers:node14.15.0-chrome86-ff82
        environment:
          ## this enables colors in the output
          TERM: xterm
    parallelism: 3
    steps:
      # - attach_workspace:
      #     at: ~/
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}

      - run: yarn cypress run --record --parallel

workflows:
  linux:
    jobs:
      - build
      - run_tests:
          name: Run Cypress Tests
          requires:
            - build
